package com.asiainfo.biapp.pec.plan.jx.link.vo;

import com.asiainfo.biapp.pec.plan.vo.McdCampSmsSchedule;
import lombok.Data;
import java.util.List;
import java.util.Map;

/**
 * MtlChannelDef generated by MyEclipse - Hibernate Tools
 */
@Data
public class McdCampChannelList implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String campId;
	private String channelId;
	private Integer contactType;
	private Short isHasVar; //是否具有替换符,0:无;1:有
	private String execContent;
	private String oneWordsContent;
	private int targetUserNums;  //目标客户群
	private int updateCycle;
	private int paramDays;  //频次控制间隔天数
	private int paramNum;   //频次控制发送次数
	private Double awardMount; //奖励金额
	private String editUrl; //采编路径
	private String handleUrl; // 办理路径
	private String sendSms ; // 短信用语
	private String adivId;  //运营位id
	private String adivName;
	private String channelAdivdId;  //资源id
	private String bossTemplateId;//Boss运营位短信模板id
	private String wcTitle; // 微信标题
	private String wcFileName;  //微信本地文件名称
	private String eventInstanceDesc;
	private String eventParamJson;
	private String cepEventId;
	private String boothId;//摊位
	private String cepSceneName;
	private String fileRemoteName;
	private String botherAvoidCustomerType;
	private String botherAvoidCustomerName;
	private String pccId;
	private int isMultiMaterial  ;
	private int isMultiAdiv  ;
	private String streamEventId;
	private String targetCustomerAttrType;

	private String wmsSceneId;

	private String marketLinkId;//营销环节
	private String marketingPlanId;//正在营销的产品
	private String marketingPlanName;//正在营销的产品名称
	private Integer cancelRecommendCycle;//实时事件，取消推荐时间配置

	private String createUser;//创建人

//	@Transient
	private String messageType;   //boss运营位  引用语类型
//	@Transient
	private String channelName;
//	@Transient
	private String functionName;
	
//	@Transient
	private Map<String, Object> extendsMap;
	
//	@Transient
	private List<McdCampSmsSchedule> smsScheduleWares; //云南短信一次性：波次
	
//	@Transient
//	private List<McdCampMaterial> mcdCampMaterialList;
	
//	@Transient
//	private List<McdCampAdivInfo> mcdCampAdivInfoList;
}
