package com.asiainfo.biapp.pec.plan.jx.enterprise.model;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

import java.util.Date;


/**
 * DimCampPri generated by MyEclipse - Hibernate Tools
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName(value = "mcd_sys_interface_def")
public class McdSysInterfaceDef implements java.io.Serializable {



	/**
	 * 
	 */
	private static final long serialVersionUID = -4519244384955951512L;


	@TableField("Callws_url_Code")
	private String callwsUrlCode;


	@TableField("Callws_Url_Name")
	private String callwsUrlName;


	@TableField("Callws_Url")
	private String callwsUrl;


	@TableField("Callws_Url_Desc")
	private String callwsUrlDesc;


	@TableField("Callws_Url_Type")
	private Short callwsUrlType;


	@TableField("OppositeType")
	private Short oppositeType;


	@TableField("CreateData")
	private Date createDate;


	@TableField("CreateUserId")
	private String createUserid;


	@TableField("Opposite_Name")
	private String oppositeName;

	@TableField("Callws_Url_class")
	private String callwsUrlClass;


	
}
